server:
  port: 9110

spring:
  application:
    name: exception-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee-service
    username: root
    password: mysql25
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
