server:
  port: 8087

spring:
  application:
    name: payment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment-service
    #url: jdbc:mysql://database-01.cfi8s6i6skce.eu-north-1.rds.amazonaws.com:3306/payment-service
    username: root
    password: mysql25
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true